### ISSUE TITLE
exrsplit - enhancement "writing exr"

### ISSUE THREAD

**Issue by gree303** [tiagoshibata/exrsplit#2]
Hi Tiago,
thanks for sharing your knowledge.
Will you add a "write-node" for output too? 
Thanks and all the best,
Chris

**Comment by tiagoshibata** [comment]
Sorry for the delay in getting this done, I was a bit busy. So, as we discussed through email, you'd want a way to build multi layer EXR from single layer files. exrsplit is made to work with multi layer and multi view files (the OpenEXR specs also define views, for e.g. stereo images). Merging should also support both of them.

Currently, exrsplit creates files with the format `view.layer.channel`, where `view` and `layer` are optional (might not exist if a single layer image is given as input), and `layer` supports nested layers (e.g. a layer named `street_objects.car.window`). What I have imagined to keep the current format is:

* A new option `-m`,`--merge` for merging channels. A list of input files and an output file are passed as positional parameters.
* To solve inconsistencies due to file naming (`car.window` is a layer `window` in layer `car` or inside a view `car`?), an argument `--view` might be specified multiple times to list names that should be used as views.

This could work like:

```
python -m exrsplit --merge car.window.exr car.door.exr merged_car.exr
Creates merged_car.exr with layers car.window and car.door
```

```
python -m exrsplit --merge --view right --view left right.ball.exr left.ball.exr right.goal.exr left.goal.exr merged_soccerfield.exr
Creates merged_soccerfield.exr with view left containing ball.exr and goal.exr, and view right containing ball.exr and goal.exr
```

Let me know if this is enough or you have other suggestions. I will be tidying up the program, adding automated tests and some features at the [develop](https://github.com/tiagoshibata/exrsplit/tree/develop) branch.

**Comment by gree303** [comment]
wow - great. Thank you so much. May I ask where to install the scripts exactly. It's looking for it in "/usr/bin/python: No module named exrsplit". but this is only a Shortcut to "/etc/alternatives/python". And there it's another shortcut to another location. 
I'm very thrilled to try it out... thank you!

**Comment by tiagoshibata** [comment]
`pip2 install -U git+https://github.com/tiagoshibata/exrsplit.git@develop` should do it. But I haven't finished the code to merge files, I will post here when it's done.

**Comment by gree303** [comment]
ayt, thx - looking forward it.

**Comment by tiagoshibata** [comment]
I have added the merge capability to [develop](https://github.com/tiagoshibata/exrsplit/tree/develop). I will add automated tests against the OpenEXR image repository sometime (possibly this weekend) to ensure it's working with most possible OpenEXR image configurations. I did some local tests with multi-layer images and it seems to be fine.

Examples:
```
$ python2 -m exrsplit ../openexr-images/Beachball/singlepart.0007.exr
1/8 - Saving 5 channels to left.exr
2/8 - Saving 5 channels to right.exr
3/8 - Saving 2 channels to right.disparityL.exr
4/8 - Saving 2 channels to right.disparityR.exr
5/8 - Saving 2 channels to right.forward.left.exr
6/8 - Saving 2 channels to right.forward.right.exr
7/8 - Saving 1 channels to right.whitebarmask.left.exr
8/8 - Saving 1 channels to right.whitebarmask.right.exr

$ python2 -m exrsplit --view right --view left -m *.exr output.exr
Saving to views right, left
1/8 - Merging left.exr
2/8 - Merging right.disparityL.exr
3/8 - Merging right.disparityR.exr
4/8 - Merging right.exr
5/8 - Merging right.forward.left.exr
6/8 - Merging right.forward.right.exr
7/8 - Merging right.whitebarmask.left.exr
8/8 - Merging right.whitebarmask.right.exr

$ python2 -m exrsplit.exrdump output.exr                                          
output.exr:
Channels:
A - HALF (1, 1)
disparityR.x - HALF (1, 1)
disparityR.y - HALF (1, 1)
B - HALF (1, 1)
forward.left.u - HALF (1, 1)
G - HALF (1, 1)
left.Z - HALF (1, 1)
left.R - HALF (1, 1)
whitebarmask.right.mask - HALF (1, 1)
whitebarmask.left.mask - HALF (1, 1)
R - HALF (1, 1)
forward.right.v - HALF (1, 1)
forward.right.u - HALF (1, 1)
forward.left.v - HALF (1, 1)
left.B - HALF (1, 1)
left.A - HALF (1, 1)
Z - HALF (1, 1)
left.G - HALF (1, 1)
disparityL.y - HALF (1, 1)
disparityL.x - HALF (1, 1)
multiView: right, left
```

**Comment by gree303** [comment]
awesome - exactly what's missing. The only thing I can't get to run is --png split output. Is the following correct? 
`python -m exrsplit --png test.exr`
No mather what I do I'm getting *.exr's.

Further, if any layer has no layername it's been saved as ".exr". In that case might be a default layer-name useful (layer1.exr,layer2.exr)

Thanks again

**Comment by tiagoshibata** [comment]
Sorry, I forgot to mention: I removed the `--png` flag in the develop branch. I'm willing to rewrite it without the imagemagick dependency, probably using Pillow. For now, you can use either one of imagemagick or graphicsmagick or exrtopng manually after splitting: `{convert,gm convert,exrtopng} image.exr image.png`.

Sorry for the inconvenience.

**Comment by tiagoshibata** [comment]
Latest `develop` is saving channels in default layer to `default_layer.exr`. Let me know if anything unexpected pops up.

**Comment by gree303** [comment]
Works like charm - thanks. 
You said the --png flag is missing in this branch. Is it capable of converting to png directly? I'm just curious, in terms of speed it would be great to extract them straight to png without writing single-layer exr before. I'm sure you have good reasons switching to another processing framework, could you share them with us?

**Comment by tiagoshibata** [comment]
Previously it wrote the image as an exr file and called imagemagick on it to convert to PNG, which added an external dependency (the imagremagick binary) and required this intermediate exr. Rewriting with Pillow would remove this intermediate exr (probably enhancing performance), but the main reason would be removing the call to an external program.

**Comment by gree303** [comment]
sounds great, thanks for the note. Please keep me updated on this git and thank you for the great work
