### ISSUE TITLE
failed with exist status 2

### ISSUE THREAD

**Issue by oumad** [tiagoshibata/exrsplit#3]
Collecting git+https://github.com/tiagoshibata/exrsplit.git@master
  Cloning https://github.com/tiagoshibata/exrsplit.git (to master) to c:\users\e504869\appdata\local\temp\pip-potx8g-build
Collecting OpenEXR (from exrsplit==0.0.1)
  Using cached OpenEXR-1.2.0.tar.gz
Installing collected packages: OpenEXR, exrsplit
  Running setup.py install for OpenEXR ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\e504869\\appdata\\local\\temp\\pip-build-apxwlc\\OpenEXR\\setup.py';f=getattr(tokenize, 'open', open)
exec'))" install --record c:\users\e504869\appdata\local\temp\pip-k6mcr2-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    copying Imath.py -> build\lib.win32-2.7
    running build_ext
    building 'OpenEXR' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    C:\Users\e504869\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I/usr/include/OpenEXR -I/usr/local/include/OpenEXR -I/opt/local/include/Op
ease\OpenEXR.obj -g -DVERSION="1.2.0"
    cl : Command line warning D9002 : ignoring unknown option '-g'
    OpenEXR.cpp
    C:\Users\e504869\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
    c:\users\e504869\appdata\local\programs\common\microsoft\visual c++ for python\9.0\vc\include\ImfVersion.h(112) : warning C4800: 'const int' : forcing value to bool 'true' or 'false' (performance warning)
    c:\users\e504869\appdata\local\programs\common\microsoft\visual c++ for python\9.0\vc\include\ImfVersion.h(113) : warning C4800: 'const int' : forcing value to bool 'true' or 'false' (performance warning)
    OpenEXR.cpp(690) : warning C4244: 'argument' : conversion from 'double' to 'const float', possible loss of data
    OpenEXR.cpp(703) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(703) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(703) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(703) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(714) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(714) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(727) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(727) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(729) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(729) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(731) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(731) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(733) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(733) : warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
    OpenEXR.cpp(858) : error C2143: syntax error : missing ')' before 'constant'
    OpenEXR.cpp(858) : error C2664: 'PyString_FromString' : cannot convert parameter 1 from 'double' to 'const char *'
    OpenEXR.cpp(858) : error C2059: syntax error : ')'
    error: command 'C:\\Users\\e504869\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\e504869\\appdata\\local\\temp\\pip-build-apxwlc\\OpenEXR\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read()
d c:\users\e504869\appdata\local\temp\pip-k6mcr2-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\e504869\appdata\local\temp\pip-build-apxwlc\OpenEXR\

* **Python version: 2.7**
* **Platform: windows**:
* **Steps to reproduce: installed Microsoft Visual C++ Compiler for Python 2.7 and copied all the libraries from openExr 2.2 downloaded on the official openExr website to the include directory then ran the pip install command**:

**Comment by tiagoshibata** [comment]
The OpenEXR Python bindings are failing to compile. The official PyPI repo is outdated ([see this issue](https://github.com/jamesbowman/openexrpython/issues/4)), you should install openexrpython from its [Git repo](https://github.com/jamesbowman/openexrpython).

The provided [requirements.txt](https://github.com/tiagoshibata/exrsplit/blob/master/requirements.txt) file should take care of that, did you try using it (with `pip install -vr requirements.txt`) instead?

**Comment by tiagoshibata** [comment]
Closing for now since the error is not related to this repository. Let me know if you still have problems.

**Comment by oumad** [comment]
I do have another problem but I think it's related to my connection and not this repo. Basically I keep getting : 

  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x034117D0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',)': /simple/api
pkg/
  Could not fetch URL https://pypi.python.org/simple/apipkg/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/apipkg/ (Caused by NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0
34116B0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',)) - skipping


Adding google DNS didn't work either. I currently don't have the time to solve this problem, but I got only one question, when I was installing the OpenExr libraries I had to add all the headers to this include directory : "C:\Users\e504869\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include" I'm pretty sure that's not the clean way to do it, but it worked. So I would like to know what is the clean way to do that? thanks.

**Comment by tiagoshibata** [comment]
Hi @oumad,

You'll have to place the headers somewhere in Visual Studio's include directories or add the folder where the headers are located to your project's include directory. [This stackoverflow answer shows both options](http://stackoverflow.com/a/335426).

I don't usually build libraries in Windows and am not sure what is the cleanest way to put them somewhere in VS's include path. Possibly changing some cmake flags to install the headers to a proper location?
